import { describe, expect, it } from "vitest";
import {
  buildEnumCheck,
  convertAutoIncrement,
  convertCreateTable,
  convertQuoting,
  convertType,
  extractCreateStatements,
  extractInsertStatements,
  normalizeDump,
  normalizeBooleanDefaults,
  splitTupleValues,
  convertTupleValues,
  planMigration,
  stripMysqlSuffixes,
} from "../lib/db-migration-plan-logic";

const dump = `-- MySQL dump 10.13
CREATE TABLE \`users\` (
  \`id\` BIGINT NOT NULL AUTO_INCREMENT,
  \`email\` VARCHAR(255) NOT NULL,
  \`role\` ENUM('user','admin') NOT NULL DEFAULT 'user',
  \`active\` TINYINT(1) NOT NULL DEFAULT 1,
  \`createdAt\` DATETIME NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`email_unique\` (\`email\`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

INSERT INTO \`users\` VALUES (1,'Niko.oeben@gmail.com','admin',1,'2026-08-01 10:00:00');
INSERT INTO \`users\` VALUES (2,'test@example.com','user',0,'2026-08-02 11:30:00');

CREATE TABLE \`billingSubscriptions\` (
  \`id\` BIGINT NOT NULL AUTO_INCREMENT,
  \`stripeSubscriptionId\` VARCHAR(255) NOT NULL,
  \`amount\` INT UNSIGNED NOT NULL,
  PRIMARY KEY (\`id\`),
  FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO \`billingSubscriptions\` VALUES (1,'sub_123',999);
`;

describe("db-migration-plan-logic", () => {
  it("normalisiert Kommentare, Leerzeilen und Zeilenenden", () => {
    const normalized = normalizeDump("-- Kommentar\r\nCREATE TABLE `t` (\r\n  `id` BIGINT\r\n);\r\n");
    expect(normalized).toBe("CREATE TABLE `t` (\n  `id` BIGINT\n);");
  });

  it("bildet MySQL-Typen konservativ auf PostgreSQL-Typen ab", () => {
    expect(convertType("TINYINT(1)", "t", "x").pgType).toBe("BOOLEAN");
    expect(convertType("BIGINT UNSIGNED", "t", "x").pgType).toBe("BIGINT");
    expect(convertType("INT", "t", "x").pgType).toBe("BIGINT");
    expect(convertType("VARCHAR(255)", "t", "x").pgType).toBe("VARCHAR(255)");
    expect(convertType("DATETIME", "t", "x").pgType).toBe("TIMESTAMP");
    expect(convertType("LONGTEXT", "t", "x").pgType).toBe("TEXT");
    expect(convertType("JSON", "t", "x").pgType).toBe("JSONB");
  });

  it("warnt bei ENUM und unbekannten Typen statt still zu migrieren", () => {
    const enumResult = convertType("ENUM('a','b')", "t", "status");
    expect(enumResult.pgType).toBe("TEXT");
    expect(enumResult.warning?.message).toContain('Spalte "status"');
    const unknown = convertType("GEOMETRY", "t", "form");
    expect(unknown.pgType).toBe("TEXT");
    expect(unknown.warning?.message).toContain("nachpruefen");
  });

  it("erzeugt CHECK-Empfehlungen nur fuer ENUM-Spalten", () => {
    expect(buildEnumCheck("users", "role", "ENUM('user','admin')")).toContain(
      'CHECK ("role" IN (\'user\', \'admin\'))',
    );
    expect(buildEnumCheck("users", "id", "BIGINT")).toBeNull();
  });

  it("konvertiert Backticks und Escape-Sequenzen", () => {
    expect(convertQuoting("`users` VALUES ('it\\'s')")).toBe('"users" VALUES (\'it\'\'s\')');
  });

  it("entfernt ENGINE/CHARSET/COLLATE-Anhaenge und AUTO_INCREMENT-Zaehler", () => {
    const stripped = stripMysqlSuffixes(") ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;");
    expect(stripped).toBe(");");
  });

  it("erkennnt AUTO_INCREMENT-Schluesselspalten als Identitaet", () => {
    const result = convertAutoIncrement("  `id` BIGINT NOT NULL AUTO_INCREMENT,", "users");
    expect(result.identity).toBe(true);
    expect(result.line).toBe('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    const other = convertAutoIncrement("  `email` VARCHAR(255),", "users");
    expect(other.identity).toBe(false);
  });

  it("findet CREATE- und INSERT-Statements im Dump", () => {
    expect(extractCreateStatements(dump)).toHaveLength(2);
    const inserts = extractInsertStatements(dump);
    expect(inserts).toHaveLength(3);
    expect(inserts.filter((i) => i.table === "users")).toHaveLength(2);
  });

  it("konvertiert ein CREATE-Statement vollstaendig nach PostgreSQL", () => {
    const [usersCreate] = extractCreateStatements(dump);
    const converted = convertCreateTable(usersCreate);
    expect(converted.tableName).toBe("users");
    expect(converted.pgStatement).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(converted.pgStatement).toContain('"active" BOOLEAN NOT NULL DEFAULT TRUE');
    expect(converted.pgStatement).toContain('"role" TEXT NOT NULL DEFAULT \'user\'');
    expect(converted.pgStatement).toContain("PRIMARY KEY (\"id\")");
    expect(converted.pgStatement).not.toContain("ENGINE");
    expect(converted.pgStatement).not.toContain("UNIQUE KEY");
    expect(converted.enumChecks[0]).toContain("users_role_enum");
  });

  it("baut einen vollstaendigen Migrationsplan mit Zaehlungen und Warnungen", () => {
    const plan = planMigration(dump);
    const tableNames = plan.tables.map((t) => t.name);
    expect(tableNames).toContain("users");
    expect(tableNames).toContain("users_enum_check");
    expect(plan.insertStatements).toHaveLength(3);
    expect(plan.expectedRowCounts).toEqual({ users: 2, billingSubscriptions: 1 });
    const foreignKeyWarnings = plan.warnings.filter((w) => w.message.includes("FOREIGN KEY"));
    expect(foreignKeyWarnings).toHaveLength(1);
    expect(foreignKeyWarnings[0].table).toBe("billingSubscriptions");
    const enumWarnings = plan.warnings.filter((w) => w.message.includes("ENUM"));
    expect(enumWarnings).toHaveLength(1);
  });

  it("erzeugt gegen die Sandbox-PG lauffaehiges SQL aus einem realistischen Dump", async () => {
    const plan = planMigration(dump);
    const sql = [
      ...plan.tables.map((t) => t.createStatement),
      ...plan.insertStatements,
    ].join("\n");
    expect(sql).not.toContain("`");
    expect(sql).not.toContain("ENGINE");
    expect(sql).toContain("INSERT INTO \"users\"");
  });
});
