import { IconSymbol } from "@/components/ui/icon-symbol";
import type { DevelopmentGuidanceStep } from "@/lib/development-guidance-logic";
import type { DetailedFileDiffPreview } from "@/lib/file-diff-logic";
import { FlatList, Modal, StyleSheet, Text, TouchableOpacity, View } from "react-native";

type DiffRow = { id: string; kind: "file" | "line" | "notice"; preview?: DetailedFileDiffPreview; line?: DetailedFileDiffPreview["lines"][number]; text?: string };

export function DiffConfirmationSheet({ step, previews, visible, onCancel, onConfirm }: { step: DevelopmentGuidanceStep | null; previews: DetailedFileDiffPreview[]; visible: boolean; onCancel: () => void; onConfirm: () => void }) {
  const rows: DiffRow[] = previews.flatMap((preview) => [{ id: `${preview.path}-file`, kind: "file" as const, preview }, ...preview.lines.map((line, index) => ({ id: `${preview.path}-${line.kind}-${index}`, kind: "line" as const, line })), ...(preview.truncated ? [{ id: `${preview.path}-more`, kind: "notice" as const, text: "Weitere geänderte Zeilen sind aus Sicherheitsgründen in dieser Vorschau ausgeblendet." }] : [])]);
  return <Modal animationType="slide" onRequestClose={onCancel} presentationStyle="pageSheet" transparent visible={visible}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.handle} /><FlatList contentContainerStyle={styles.content} data={rows} keyExtractor={(row) => row.id} ListHeaderComponent={<><Text style={styles.eyebrow}>VOR AUSFÜHRUNG PRÜFEN</Text><Text style={styles.title}>{step?.title ?? "Vorgeschlagener Schritt"}</Text><Text style={styles.description}>{previews.length ? "Überprüfe die lokalen Code-Änderungen, bevor du diesen Schritt ausdrücklich ausführst. Diese Ansicht übernimmt keine Änderung." : "Dieser Schritt führt keine lokalen Code-Änderungen aus. Prüfe den Zweck und bestätige ihn bewusst."}</Text>{previews.length ? <Text style={styles.diffLabel}>CODE-DIFF · {previews.length} DATEI(EN)</Text> : <View style={styles.noDiff}><IconSymbol name="doc.text.fill" size={17} color="#93A8BA" /><Text style={styles.noDiffText}>Keine lokalen Code-Diffs vorhanden.</Text></View>}</>} ListFooterComponent={<View style={styles.actions}><TouchableOpacity accessibilityRole="button" activeOpacity={0.75} onPress={onCancel} style={styles.cancel}><Text style={styles.cancelText}>Abbrechen</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" activeOpacity={0.75} onPress={onConfirm} style={styles.confirm}><Text style={styles.confirmText}>Schritt ausführen</Text><IconSymbol name="arrow.right" size={16} color="#04151C" /></TouchableOpacity></View>} renderItem={({ item }) => { if (item.kind === "file" && item.preview) return <View style={styles.fileHeader}><Text numberOfLines={1} style={styles.filePath}>{item.preview.path}</Text><Text style={styles.fileCounts}>+{item.preview.addedLines} / −{item.preview.removedLines}</Text></View>; if (item.kind === "notice") return <Text style={styles.notice}>{item.text}</Text>; const line = item.line!; return <View style={[styles.lineRow, line.kind === "added" ? styles.added : line.kind === "removed" ? styles.removed : styles.context]}><Text style={styles.lineNumber}>{line.lineNumber}</Text><Text numberOfLines={2} style={styles.lineText}>{line.kind === "added" ? "+ " : line.kind === "removed" ? "− " : "  "}{line.content || " "}</Text></View>; }} showsVerticalScrollIndicator={false} /></View></View></Modal>;
}

const styles = StyleSheet.create({
  backdrop: { backgroundColor: "rgba(2,6,12,0.72)", flex: 1, justifyContent: "flex-end" }, sheet: { backgroundColor: "#101722", borderColor: "#31445A", borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, maxHeight: "88%" }, handle: { alignSelf: "center", backgroundColor: "#526478", borderRadius: 99, height: 4, marginTop: 9, width: 44 }, content: { padding: 16, paddingBottom: 22 }, eyebrow: { color: "#8297AD", fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginTop: 8 }, title: { color: "#F0F6FB", fontSize: 20, fontWeight: "900", lineHeight: 26, marginTop: 5 }, description: { color: "#A9B8C8", fontSize: 12, lineHeight: 18, marginTop: 8 }, diffLabel: { color: "#718BA5", fontSize: 10, fontWeight: "900", letterSpacing: 1, marginBottom: 8, marginTop: 17 }, noDiff: { alignItems: "center", backgroundColor: "#18212D", borderColor: "#33475D", borderRadius: 12, borderWidth: 1, flexDirection: "row", gap: 8, marginTop: 15, minHeight: 48, paddingHorizontal: 12 }, noDiffText: { color: "#A8B8C8", fontSize: 12, fontWeight: "700" }, fileHeader: { alignItems: "center", backgroundColor: "#182432", borderColor: "#36506A", borderRadius: 10, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 8, minHeight: 40, paddingHorizontal: 10 }, filePath: { color: "#D9EBF8", flex: 1, fontFamily: "monospace", fontSize: 11, fontWeight: "800", marginRight: 10 }, fileCounts: { color: "#72E1B1", fontFamily: "monospace", fontSize: 11, fontWeight: "900" }, lineRow: { flexDirection: "row", marginTop: 1, minHeight: 28, paddingHorizontal: 7, paddingVertical: 5 }, added: { backgroundColor: "rgba(69,217,150,0.13)" }, removed: { backgroundColor: "rgba(255,107,122,0.13)" }, context: { backgroundColor: "#111A25" }, lineNumber: { color: "#718397", fontFamily: "monospace", fontSize: 10, marginRight: 8, textAlign: "right", width: 26 }, lineText: { color: "#D3E0EA", flex: 1, fontFamily: "monospace", fontSize: 10, lineHeight: 15 }, notice: { color: "#F2C979", fontSize: 11, lineHeight: 16, marginTop: 7 }, actions: { flexDirection: "row", gap: 10, marginTop: 18 }, cancel: { alignItems: "center", borderColor: "#46596E", borderRadius: 12, borderWidth: 1, flex: 1, justifyContent: "center", minHeight: 48 }, cancelText: { color: "#B8C6D5", fontSize: 13, fontWeight: "900" }, confirm: { alignItems: "center", backgroundColor: "#52D8FF", borderRadius: 12, flex: 1.25, flexDirection: "row", gap: 7, justifyContent: "center", minHeight: 48 }, confirmText: { color: "#04151C", fontSize: 13, fontWeight: "900" },
});
