import { useMemo } from "react";
import { IconSymbol } from "@/components/ui/icon-symbol";
import type { DevelopmentGuidanceStep } from "@/lib/development-guidance-logic";
import type { DetailedFileDiffPreview } from "@/lib/file-diff-logic";
import { FlatList, Modal, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { withAlpha } from "@/lib/theme-color-utils";
import { useColors } from "@/hooks/use-colors";
import { accentAlpha, glassDepth, glassSurface } from "@/lib/design/future-glass";

type DiffRow = { id: string; kind: "file" | "line" | "notice"; preview?: DetailedFileDiffPreview; line?: DetailedFileDiffPreview["lines"][number]; text?: string };

export function DiffConfirmationSheet({ step, previews, visible, onCancel, onConfirm }: { step: DevelopmentGuidanceStep | null; previews: DetailedFileDiffPreview[]; visible: boolean; onCancel: () => void; onConfirm: () => void }) {
    const colors = useColors();
    const styles = useMemo(() => createStyles(colors), [colors]);
  const rows: DiffRow[] = previews.flatMap((preview) => [{ id: `${preview.path}-file`, kind: "file" as const, preview }, ...preview.lines.map((line, index) => ({ id: `${preview.path}-${line.kind}-${index}`, kind: "line" as const, line })), ...(preview.truncated ? [{ id: `${preview.path}-more`, kind: "notice" as const, text: "Weitere geänderte Zeilen sind aus Sicherheitsgründen in dieser Vorschau ausgeblendet." }] : [])]);
  return <Modal animationType="slide" onRequestClose={onCancel} presentationStyle="pageSheet" transparent visible={visible}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.handle} /><FlatList contentContainerStyle={styles.content} data={rows} keyExtractor={(row) => row.id} ListHeaderComponent={<><Text style={styles.eyebrow}>VOR AUSFÜHRUNG PRÜFEN</Text><Text style={styles.title}>{step?.title ?? "Vorgeschlagener Schritt"}</Text><Text style={styles.description}>{previews.length ? "Überprüfe die lokalen Code-Änderungen, bevor du diesen Schritt ausdrücklich ausführst. Diese Ansicht übernimmt keine Änderung." : "Dieser Schritt führt keine lokalen Code-Änderungen aus. Prüfe den Zweck und bestätige ihn bewusst."}</Text>{previews.length ? <Text style={styles.diffLabel}>CODE-DIFF · {previews.length} DATEI(EN)</Text> : <View style={styles.noDiff}><IconSymbol name="doc.text.fill" size={17} color={glassSurface.textMuted} /><Text style={styles.noDiffText}>Keine lokalen Code-Diffs vorhanden.</Text></View>}</>} ListFooterComponent={<View style={styles.actions}><TouchableOpacity accessibilityRole="button" activeOpacity={0.75} onPress={onCancel} style={styles.cancel}><Text style={styles.cancelText}>Abbrechen</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" activeOpacity={0.75} onPress={onConfirm} style={styles.confirm}><Text style={styles.confirmText}>Schritt ausführen</Text><IconSymbol name="arrow.right" size={16} color={glassDepth.void} /></TouchableOpacity></View>} renderItem={({ item }) => { if (item.kind === "file" && item.preview) return <View style={styles.fileHeader}><Text numberOfLines={1} style={styles.filePath}>{item.preview.path}</Text><Text style={styles.fileCounts}>+{item.preview.addedLines} / −{item.preview.removedLines}</Text></View>; if (item.kind === "notice") return <Text style={styles.notice}>{item.text}</Text>; const line = item.line!; return <View style={[styles.lineRow, line.kind === "added" ? styles.added : line.kind === "removed" ? styles.removed : styles.context]}><Text style={styles.lineNumber}>{line.lineNumber}</Text><Text numberOfLines={2} style={styles.lineText}>{line.kind === "added" ? "+ " : line.kind === "removed" ? "− " : "  "}{line.content || " "}</Text></View>; }} showsVerticalScrollIndicator={false} /></View></View></Modal>;
}

function createStyles(colors: ReturnType<typeof useColors>) {
  return StyleSheet.create({
  backdrop: { backgroundColor: glassDepth.glass, flex: 1, justifyContent: "flex-end" }, sheet: { backgroundColor: glassDepth.void, borderColor: glassSurface.borderStrong, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, maxHeight: "88%" }, handle: { alignSelf: "center", backgroundColor: glassDepth.deep, borderRadius: 99, height: 4, marginTop: 9, width: 44 }, content: { padding: 16, paddingBottom: 22 }, eyebrow: { color: glassSurface.textMuted, fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginTop: 8 }, title: { color: glassSurface.textSecondary, fontSize: 20, fontWeight: "900", lineHeight: 26, marginTop: 5 }, description: { color: glassSurface.textSecondary, fontSize: 12, lineHeight: 18, marginTop: 8 }, diffLabel: { color: glassSurface.textMuted, fontSize: 10, fontWeight: "900", letterSpacing: 1, marginBottom: 8, marginTop: 17 }, noDiff: { alignItems: "center", backgroundColor: glassDepth.void, borderColor: glassSurface.borderStrong, borderRadius: 12, borderWidth: 1, flexDirection: "row", gap: 8, marginTop: 15, minHeight: 48, paddingHorizontal: 12 }, noDiffText: { color: glassSurface.textSecondary, fontSize: 12, fontWeight: "700" }, fileHeader: { alignItems: "center", backgroundColor: glassDepth.void, borderColor: glassSurface.borderStrong, borderRadius: 10, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 8, minHeight: 40, paddingHorizontal: 10 }, filePath: { color: glassSurface.textSecondary, flex: 1, fontFamily: "monospace", fontSize: 11, fontWeight: "800", marginRight: 10 }, fileCounts: { color: colors.success, fontFamily: "monospace", fontSize: 11, fontWeight: "900" }, lineRow: { flexDirection: "row", marginTop: 1, minHeight: 28, paddingHorizontal: 7, paddingVertical: 5 }, added: { backgroundColor: withAlpha(colors.success, 0.13) }, removed: { backgroundColor: accentAlpha("red", 0.13) }, context: { backgroundColor: glassDepth.void }, lineNumber: { color: glassSurface.textMuted, fontFamily: "monospace", fontSize: 10, marginRight: 8, textAlign: "right", width: 26 }, lineText: { color: glassSurface.textSecondary, flex: 1, fontFamily: "monospace", fontSize: 10, lineHeight: 15 }, notice: { color: colors.warning, fontSize: 11, lineHeight: 16, marginTop: 7 }, actions: { flexDirection: "row", gap: 10, marginTop: 18 }, cancel: { alignItems: "center", borderColor: glassSurface.borderStrong, borderRadius: 12, borderWidth: 1, flex: 1, justifyContent: "center", minHeight: 48 }, cancelText: { color: glassSurface.textSecondary, fontSize: 13, fontWeight: "900" }, confirm: { alignItems: "center", backgroundColor: colors.tint, borderRadius: 12, flex: 1.25, flexDirection: "row", gap: 7, justifyContent: "center", minHeight: 48 }, confirmText: { color: glassDepth.void, fontSize: 13, fontWeight: "900" },
  });
}
