import { IconSymbol } from "@/components/ui/icon-symbol";
import type { DevelopmentGuidanceAction, DevelopmentGuidanceStep } from "@/lib/development-guidance-logic";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";

export function NextStepGuide({ guidance, completion, actionMessage, onAction }: { guidance: { primary: DevelopmentGuidanceStep; secondary: DevelopmentGuidanceStep[] }; completion?: string; actionMessage?: string; onAction: (action: DevelopmentGuidanceAction) => void }) {
  const firstSuggestion = guidance.secondary[0];
  const secondSuggestion = guidance.secondary[1];
  return <View style={styles.section}><Text style={styles.kicker}>ENTWICKLUNGSFÜHRUNG</Text><Text style={styles.heading}>Als nächste sinnvolle Schritte bieten sich diese Aktionen an.</Text><GuideCard step={guidance.primary} prominent onPress={onAction} />{completion ? <View style={styles.completion}><IconSymbol name="checkmark.circle.fill" size={18} color="#52D878" /><Text style={styles.completionText}>Aufgabe abgeschlossen · {completion}</Text></View> : null}{actionMessage ? <Text style={styles.actionMessage}>{actionMessage}</Text> : null}<View style={styles.suggestions}>{firstSuggestion ? <GuideCard step={firstSuggestion} compact onPress={onAction} /> : null}{secondSuggestion ? <GuideCard step={secondSuggestion} compact onPress={onAction} /> : null}</View></View>;
}

function GuideCard({ step, prominent = false, compact = false, onPress }: { step: DevelopmentGuidanceStep; prominent?: boolean; compact?: boolean; onPress: (action: DevelopmentGuidanceAction) => void }) {
  const warning = step.tone === "warning";
  return <View style={[styles.card, prominent && styles.cardProminent, warning && styles.cardWarning, compact && styles.cardCompact]}><View style={styles.cardHeader}><View style={[styles.iconTile, warning && styles.iconTileWarning]}><IconSymbol name={warning ? "exclamationmark.triangle.fill" : step.tone === "ready" ? "checkmark.circle.fill" : "bolt.fill"} size={17} color={warning ? "#F6BA5E" : "#52D8FF"} /></View><Text numberOfLines={1} style={styles.eyebrow}>{step.eyebrow}</Text></View><Text style={[styles.title, compact && styles.titleCompact]}>{step.title}</Text><Text numberOfLines={compact ? 3 : undefined} style={styles.description}>{step.description}</Text><TouchableOpacity accessibilityRole="button" activeOpacity={0.76} onPress={() => onPress(step.action)} style={[styles.action, warning && styles.actionWarning]}><Text style={[styles.actionText, warning && styles.actionTextWarning]}>{step.actionLabel}</Text><IconSymbol name="arrow.right" size={15} color={warning ? "#2A1803" : "#04151C"} /></TouchableOpacity></View>;
}

const styles = StyleSheet.create({
  section: { marginBottom: 25 }, kicker: { color: "#75889D", fontSize: 10, fontWeight: "900", letterSpacing: 1.2, marginBottom: 6 }, heading: { color: "#EAF1F9", fontSize: 20, fontWeight: "800", letterSpacing: -0.35, lineHeight: 28, marginBottom: 13 }, card: { backgroundColor: "#141B27", borderColor: "#2A3A50", borderRadius: 18, borderWidth: 1, flex: 1, padding: 13 }, cardProminent: { backgroundColor: "#172331", borderColor: "#3B6277", padding: 15 }, cardWarning: { backgroundColor: "#241D14", borderColor: "#6E542A" }, cardCompact: { minHeight: 214, minWidth: 245 }, cardHeader: { alignItems: "center", flexDirection: "row", gap: 8, marginBottom: 11 }, iconTile: { alignItems: "center", backgroundColor: "#153443", borderRadius: 9, height: 30, justifyContent: "center", width: 30 }, iconTileWarning: { backgroundColor: "#3A2D18" }, eyebrow: { color: "#8FA1B4", flex: 1, fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, title: { color: "#F1F6FB", fontSize: 16, fontWeight: "900", lineHeight: 21, marginBottom: 6 }, titleCompact: { fontSize: 14, lineHeight: 19 }, description: { color: "#A8B7C7", fontSize: 12, lineHeight: 18 }, action: { alignItems: "center", backgroundColor: "#52D8FF", borderRadius: 12, flexDirection: "row", gap: 6, justifyContent: "center", marginTop: 14, minHeight: 44, paddingHorizontal: 12 }, actionWarning: { backgroundColor: "#F6BA5E" }, actionText: { color: "#04151C", fontSize: 12, fontWeight: "900" }, actionTextWarning: { color: "#2A1803" }, completion: { alignItems: "center", flexDirection: "row", gap: 8, marginTop: 13 }, completionText: { color: "#68D88B", fontSize: 12, fontWeight: "800" }, actionMessage: { color: "#83DDB2", fontSize: 11, fontWeight: "700", lineHeight: 16, marginTop: 10 }, suggestions: { flexDirection: "row", gap: 10, marginTop: 13, overflow: "hidden" },
});
